### ISSUE TITLE
New "Acceptance Testing" section for RFCs?

### ISSUE THREAD

**Issue by epage** [rust-lang/this-week-in-rust#3236]
Some times it can be a challenge to get testers for an RFC implementation to get the feedback to know if its ready for stablization (see [Mechanism for beta testing unstable features](https://internals.rust-lang.org/t/mechanism-for-beta-testing-unstable-features/14280)).

What if we had a new section "Acceptance Testing" where we queued up RFCs that are are at stage of needing general feedback, either as part of an intermediate design milestone (e.g. https://github.com/rust-lang/rfcs/pull/3243#) or in prep for stablization (e.g. https://github.com/rust-lang/cargo/issues/8415#issuecomment-1112618913)?  They'd need to link out to a test plan (defining what you are looking, link to how to use the feature, link to how to use it with nightly, where to apply feedback, etc).

**Comment by jonhoo** [comment]
In the interest of continuing to leave a trail for things related to this effort, see also [The case for a new release channel: testing](https://internals.rust-lang.org/t/the-case-for-a-new-relese-channel-testing/14412/32), [Survey of "High Impact" Features](https://internals.rust-lang.org/t/survey-of-high-impact-features/14536/20), [RFC: Preview for Unstable Features](https://github.com/rust-lang/rfcs/pull/3120), and ultimately [this comment](https://github.com/rust-lang/rfcs/pull/3120#issuecomment-836921374).

I love the idea of a "call for testing" in TWiR. My main concern continues to be the ability to get widespread testing when it requires nightly.

**Comment by U007D** [comment]
@epage Interesting thoughts.  Would it help if the section were titled something more "call-to-action" oriented e.g. "Call for Testing"?
@jonhoo I read the links you provided (only most of the RFC: Preview for Unstable Features) + your linked comment.  I have personal opinions on where we should land, but before I get to those, to address @epage's concern, it would be a shame to let perfect be the enemy of good.

To that end, a section with a call to action and clear instructions (or a link to clear instructions) that would evolve as the feature stabilization process does would allow us to move forward (if we elected to) quickly, while still preserving the option to evolve the stabilization process.

Definitely something to discuss with @nellshamrell and the rest of the TWiR editors, but if either of you have a draft of what you'd like to see the section look like please share it here, otherwise let us know.  I'm happy bring up the topic for discussion with the other editors.

**Comment by epage** [comment]
Draft: comes before "Final Comment Period"
```md
### Call For Testing

An important step for RFC implementation is for people to experiment with the implementation and give feedback, especially before stablization.  The following RFCs are at point where user testing is needed before moving forward:

Pre-Stablization
- [RFC 2906 Tracking Issue](https://github.com/rust-lang/cargo/issues/8415): Testing steps **LINKME**
```

**Comment by Muscraft** [comment]
Having a summary of the changes might be nice as well. I know for `RFC 2906` we made changes from what the RFC called for and [there is a summary](https://github.com/rust-lang/cargo/issues/8415#issuecomment-1112618913) because of that. The link to the tracking issue could be just a link to the most recent summary as well.

**Comment by nellshamrell** [comment]
Adding this section sounds good to me - and it's a great way to increase participation!

**Comment by Muscraft** [comment]
Unless there is more to discuss on how the future looks for this section I think #3249 closes this issue

**Comment by U007D** [comment]
In working through this, I think the simplest way forward is to create a new label (e.g. `call-for-testing`) that authors and implementers can apply to their RFCs/tracking items, etc., as appropriate.

(For future consideration, I remain convinced that we will get better uptake when the line items come with specific testing instructions; this is something we can iterate on over time.)

I have added the two RFCs explicitly called out in this thread [RFC 3243](https://github.com/rust-lang/rfcs/pull/3243) and [TI 8415](https://github.com/rust-lang/cargo/issues/8415#issuecomment-1112618913) to this week's TWiR and will keep an eye out for feedback.

**Going forward, I propose building the section based on new results from [this query](https://github.com/rust-lang/rfcs/labels/call-for-testing).  If you have suggestions on any of this please share, otherwise if this looks good I'll figure out how to create a new `call-for-testing` label and we will proceed from there.**

**Comment by Muscraft** [comment]
I don't know if you saw but I opened a PR for TI 8415 already in #3256

**Comment by U007D** [comment]
@Muscraft Great catch.  I've edited the proposed query to search only for the label, per your suggestion.

I have added the `call-for-testing` tag to `rust-lang/rfcs` repo, but am not credentialled to do it for tracking issues which live in the `rust-lang/rust` repo.  Is this something you can help with?  @nellshamrell?

Label: call-for-testing
Color: #36E885
Description: Add this label + test notes in comments to be included in TWiR `Call for Testing` section.

**Comment by U007D** [comment]
> This also has the benefit that each RFC that is looking for testing would be in every TWiR until testers are no longer needed.

I think it would make sense to have these expire automatically so as not to dominate the newsletter with aging content.  If I remove the tag for all listed content, the issue owner could add it again when it is time for another test run (or if they simply wanted to be listed for a second week in a row).

What do you think of that system?

**Comment by Muscraft** [comment]
> I have added the call-for-testing tag to rust-lang/rfcs repo, but am not credentialled to do it for tracking issues which live in the rust-lang/rust repo. Is this something you can help with? 

I can't help with this, I do not have permission to add labels

> I think it would make sense to have these expire automatically so as not to dominate the newsletter with aging content. If I remove the tag when I add the content each week, the issue owner could add it again when it is time for another test run (or if they simply wanted to be listed for another consecutive week).
> What do you think of that system?

I think it will be perfect to start with and we can tweak it as we go. I can see why it is better to have to opt-in each week or every time there is a need for more testers

**Comment by U007D** [comment]
Great, I agree.  We'll start with this process as described here and will evolve it as the need arises.
