### ISSUE TITLE
How to get community events included without having meetup account

### ISSUE THREAD

**Issue by hamidrezakp** [rust-lang/this-week-in-rust#3635]
Hi,
I am one of the organizers of the Rust Iran Meetup.
I have added all the meetups to Rust community calendar but our meetups aren't showing up in TWiR.

I have seen you are using a python script to fetch Rust events from Meetup.com, but shouldn't we fetch events from community calendar?
Anyway, Meetup.com is not free of charge, or i do not know of any way to get free account (tell me if there is any discount for Rust communities).

How should i include our meetup to be in TWiR without needing to manually insert it there?

Thanks

**Comment by andrewpollack** [comment]
Hello,

Thank you for reaching out @hamidrezakp ! I can speak on this, since I helped compile the events for the previous issue

You are correct that we do fetch meetings from both the Rust community calendar, as well as from Meetup.com. To clarify, we do not require nor expect folks to post to Meetup.com for events, and are always looking to include events from any source that gives readers explicit details about the event

For the Rust Iran Meetup, I did see on the calendar that there is an event planned for September 22; however, when looking at the website landing page at https://rust-meetup.ir/ , I do not see an event description for September 22. To best help readers access information for events, links in the newsletter will directly link to event descriptions (e.g. for the August 18th event, we linked to https://rust-meetup.ir/2022/08/18/8th-meetup.html ), and so the lack of a description for the September 22 event at https://rust-meetup.ir/ made it unclear where to point folks to

All said, to best make readers aware of event details, please make an event description that we can point to (e.g. https://rust-meetup.ir/2022/08/18/8th-meetup.html), and we'll make sure that the events are included. I apologize for missing the event's inclusion in the latest entry, and hope that this is helpful

**Comment by hamidrezakp** [comment]
Hi Andrew,

Thank you for your complete response.
You are right, i will create events on the website and create pull request to add it to the next issue.
So i'm closing this one,
