### ISSUE TITLE
What's the correct way to submitt an issue for the "Call for Participation" section

### ISSUE THREAD

**Issue by weiznich** [rust-lang/this-week-in-rust#5334]
This week in Rust links to [this users.rust-lang.org thread](https://users.rust-lang.org/t/twir-call-for-participation/4821/622) for submitting issues for the "Call for Participation" section. I remember that submitting issues there in the past resulted in having them in the corresponding section, but for the last two times I've posted some issue there it was not picked up. Therefore I'm unsure if that is not the right place anymore, or if I just was unlucky to post both issues to close to the publication date. It would be great to have some indication what could be done on my side to improve the likelyhood that such issues appear in the weekly newsletter.

**Comment by bennyvasquez** [comment]
Hi there! I'm the editor for that section, and I'm very sorry for the confusion! In looking at the most recent one there, it looks like it was a discussion rather than a specific issue or task. Since this section could get out of hand quite quickly, my intention is to limit it to just issues that have a clearly defined task that can be achieved. 

Thanks for reaching out and please do let me know if I can answer any other questions!
