### ISSUE TITLE
Very light font can be difficult to read

### ISSUE THREAD

**Issue by piedoom** [rust-lang/this-week-in-rust#708]
Thanks for this awesome resource!  I have a suggestion to make:

I'd like to recommend against using such a light font for all body items on "TWIR".  It makes things very difficult to read sometimes. 

![image](https://user-images.githubusercontent.com/8846211/44814597-d7e59880-aba2-11e8-922c-51d40bd33670.png)

I could be wrong, but this looks like Helvetica or Arial with a very light weight.  I would suggest at least bumping up the weight to 400, or even changing the font to something more legible in general (like Lato, [InterUI](https://rsms.me/inter/), etc.)

**Comment by piedoom** [comment]
Edit: I tested on my windows machine, and it seems like it's just a behavior of Macs using Helvetica.  In that case, I would perhaps enforce the usage of Arial through all browsers.

**Comment by nasa42** [comment]
Assuming this is a localised issue with your system and not with the website (as we use widely available fonts `"Helvetica Neue", Helvetica, Arial, sans-serif` (in fallback order), I'll close it.

**Comment by zofrex** [comment]
I'm having this same issue, also on a Mac. It's genuinely hard for me to read these posts, even if I increase the font size in my browser it doesn't help much because it remains very skinny.

It's also rendering very poorly from an aesthetic point of view - lines are inconsistent widths and corners look a little pixelated, I think probably also due to the skinniness:

![Screenshot of the This Week In Rust newsletter](https://i.imgur.com/ngdaPRx.png)

I have only very mild visual impairment (20/20 vision corrected) and this is hard for me to read. It would be nice to see a fix here, even if it works on someone else's machine it certainly doesn't work on mine.

Technical details:

- OS: macOS Cataline 10.15.6
- Browser: Chrome 86.0.4240.80 (problem does not occur in Safari or Firefox)
- Screen is a non-hiDPI external display

**Comment by ali** [comment]
I noticed this as well. The page uses Helvetica with a light font weight instead of a normal font weight, which I found slightly difficult to read. For context, I'm on a Mac with a hiDPI screen. I tracked this down to [the `font-weight: 300` style in `_base.scss`](https://github.com/rust-lang/this-week-in-rust/blob/af1aca49c6472c80b4b0e37568ba2d226ea73135/themes/rusted/static/css/_base.scss#L20).

| light (300) font weight (currently used) | normal (400) font weight (default) |
|--------|-------|
| <img width="690" alt="Screen Shot 2020-10-15 at 12 04 49 PM" src="https://user-images.githubusercontent.com/515861/96156180-cb397100-0ede-11eb-95b1-c5102d04356b.png"> | <img width="689" alt="Screen Shot 2020-10-15 at 12 04 29 PM" src="https://user-images.githubusercontent.com/515861/96156185-cbd20780-0ede-11eb-9768-5d01ed584c38.png"> |

**Comment by teor2345** [comment]
I am seeing a similar issue on my iPad Mini 4, the weights appear midway between the screenshots in the post above this one.

https://github.com/rust-lang/this-week-in-rust/issues/708#issuecomment-709429391

**Comment by nellshamrell** [comment]
I would love help on this one from the community!

**Comment by teor2345** [comment]
I just checked on macOS 10.13.6, the results seem to depend on both the browser and the display.

I suspect they may also depend on the display's resolution, any HiDPI settings, and LCD font smoothing settings - but I have't checked.

Chromium: mostly unreadable, worst on MacBook Pro 2017 and "LG Full HD" display
Safari: mostly readable, worse on MacBook Pro 2017 display
Firefox: all readable, a little worse on "LG Full HD" display

**Comment by ibraheemdev** [comment]
I'll get started on a dark mode for the web version

**Comment by teor2345** [comment]
@ibraheemdev I think the font is light because of the "weight" setting (the thickness of the lines), not the "colour" setting.

**Comment by ibraheemdev** [comment]
#1594 addresses the font weight issue. But a dark mode would help as well
